/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface CreateShowDto {
  /**
   * @minLength 0
   * @maxLength 150
   */
  showName: string;
  venueId: number;
  showTypeId: number;
  /** @nullable */
  description?: string | null;
  ageRestrictionId: number;
  /** @nullable */
  warningDescription?: string | null;
  startDate: string;
  endDate: string;
  /** @nullable */
  ticketTypeId?: number | null;
  /** @nullable */
  imagesUrl?: string | null;
  /** @nullable */
  videosUrl?: string | null;
}
