/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface ForgotPasswordDto {
  /** @minLength 1 */
  email: string;
}
