/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface RefreshTokenDto {
  /** @minLength 1 */
  accessToken: string;
  /** @minLength 1 */
  refreshToken: string;
}
