/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface RegisterDto {
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /** @minLength 1 */
  confirmPassword: string;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /** @nullable */
  phoneNumber?: string | null;
}
