/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface ResetPasswordDto {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  token: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
  /** @minLength 1 */
  confirmPassword: string;
}
