/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface RoleDto {
  roleId?: number;
  /** @nullable */
  roleName?: string | null;
  canCreate?: boolean;
  canRead?: boolean;
  canEdit?: boolean;
  canDelete?: boolean;
}
